# Generated by Django 5.2 on 2026-04-05 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Funds Ready'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('reminder_30d_sent', models.BooleanField(default=False)),
                ('reminder_7d_sent', models.BooleanField(default=False)),
                ('reminder_1d_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='leases.lease')),
            ],
            options={
                'db_table': 'payments_paymentschedule',
                'ordering': ['due_date'],
            },
        ),
    ]
