# Generated by Django 5.2 on 2026-04-05 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('unit_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('cheque_pattern', models.IntegerField(choices=[(1, 'Annual (1 cheque)'), (2, '6-monthly (2 cheques)'), (3, '4-monthly (3 cheques)'), (4, 'Quarterly (4 cheques)'), (6, 'Bi-monthly (6 cheques)')])),
                ('start_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leases_lease',
            },
        ),
    ]
