# Generated by Django 5.2 on 2026-08-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="lease",
            name="country",
            field=models.CharField(default="AE", max_length=2),
        ),
        migrations.AddField(
            model_name="lease",
            name="currency",
            field=models.CharField(default="AED", max_length=3),
        ),
        migrations.AlterField(
            model_name="lease",
            name="area",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="lease",
            name="cheque_pattern",
            field=models.IntegerField(
                choices=[
                    (1, "Annual (1 cheque)"),
                    (2, "6-monthly (2 cheques)"),
                    (3, "4-monthly (3 cheques)"),
                    (4, "Quarterly (4 cheques)"),
                    (6, "Bi-monthly (6 cheques)"),
                    (12, "Monthly (12 cheques)"),
                ]
            ),
        ),
    ]
