# Generated by Django 5.2 on 2026-08-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0002_lease_city_lease_country_lease_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="postal_code",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="lease",
            name="subdivision",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
