# Generated by Django 5.2 on 2026-08-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0003_lease_postal_code_lease_subdivision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="unit_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
