# Generated by Django 5.2 on 2026-08-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0004_alter_lease_unit_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="contacts",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lease",
            name="home_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "Apartment"),
                    ("villa", "Villa"),
                    ("townhouse", "Townhouse"),
                    ("commercial", "Commercial"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="lease_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
