# Generated by Django 5.2 on 2026-04-06 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20)),
                ('reminder_type', models.CharField(help_text='30d, 7d, or 1d', max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('payment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='payments.paymentschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reminders_reminderlog',
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('payment_schedule', 'channel', 'reminder_type'), name='unique_reminder_per_cheque_channel_type')],
            },
        ),
    ]
