# Generated by Django 5.2 on 2026-04-06 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('lease', 'Tenancy Contract'), ('ejari', 'EJARI Certificate'), ('other', 'Other')], default='other', max_length=20)),
                ('s3_key', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
