# Generated by Django 5.2 on 2026-08-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("lease", "Tenancy Contract"),
                    ("ejari", "Ejari Certificate"),
                    ("emirates_id", "Emirates ID"),
                    ("passport", "Passport"),
                    ("license", "Driver's License"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
