# Generated by Django 5.2 on 2026-08-09 22:23

import ark.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_verified_onetimecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="Asia/Dubai", max_length=64),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=16,
                validators=[ark.users.models.validate_international_phone],
            ),
        ),
    ]
