# Generated by Django 5.2 on 2026-07-23 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaitlistSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("expat", "Expat relocating"),
                            ("family", "Couple or family"),
                            ("first_time_renter", "First-time renter"),
                            ("property_manager", "Property manager"),
                            ("other", "Other"),
                        ],
                        default="tenant",
                        max_length=32,
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                ("referral_count", models.PositiveIntegerField(default=0)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="waitlist.waitlistsignup",
                    ),
                ),
            ],
            options={
                "ordering": ("-referral_count", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["referral_code"], name="waitlist_wa_referra_93dace_idx"
                    ),
                    models.Index(
                        fields=["-referral_count", "created_at"],
                        name="waitlist_wa_referra_7f962d_idx",
                    ),
                ],
            },
        ),
    ]
